import {AlgorithmNode, CellType, enumerate, Labyrinth, NodePrioQueue, Position, PositionSet, SearchState} from "./data";
import {ALGORITHM_LIST, AlgorithmFunction, LabyrinthSolver} from "./algorithms";

// to draw the output a 2d canvas is used
const canvas = document.getElementById('main') as HTMLCanvasElement;
const ctx = canvas.getContext('2d')!;

const COLOR_BG = "black"
const COLOR_OBSTACLE = "rgb(90,90,90)"
const COLOR_START = "pink"
const COLOR_GOAL = "cyan"
const COLOR_VISITED = "red"
const COLOR_FRONTIER = "yellow"
const COLOR_PATH = "green"


const LAB_ROWS = Math.floor(window.innerHeight / 5);
const LAB_COLS = Math.floor(window.innerWidth / 5);
const START_POS = new Position(Math.floor(LAB_ROWS / 2), Math.floor(LAB_COLS / 2));
const END_POS = new Position(LAB_ROWS - 2, LAB_COLS - 2);
const OBSTACLE_DENSITY = .1;

/**
 * Resizes the canvas to match the browser window
 */
function setSize() {
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;

    drawLabyrinth();
}

/**
 * Clear the entire canvas
 */
function resetWindow() {
    ctx.fillStyle = COLOR_BG;
    ctx.fillRect(0, 0, canvas.width, canvas.height);
}

/**
 * Update the window title
 */
function setTitle(title: string) {
    document.title = title
}

// state variables
/**
 * the algorithm used when starting a new search process
 */
let selectedAlgorithm: AlgorithmFunction | undefined;
/**
 * the labyrinth currently to be searched
 */
let labyrinth: Labyrinth | undefined;
/**
 * whether the search should be simulated or not
 * will be set to true when a new search is started
 */
let simulated: boolean;
/**
 * this is generator used to run the algorithm
 * calling next on it gets you the next 'printable' step of the algorithm
 * this is undefined if no algorithm is running
 */
let runningAlgorithm: LabyrinthSolver | undefined;
/**
 * this is a reference to the last state generated by `runningAlgorithm
 */
let currentState: SearchState | undefined;
let active = true;

/**
 * draws the labyrinth
 */
function drawLabyrinth() {
    resetWindow();
    if(labyrinth === undefined) return;

    //calculate the cell size
    const cell_height = canvas.height / labyrinth.rows
    const cell_width = canvas.width / labyrinth.cols

    /**
     * the size of the gap in between cells
     * @min 0
     * @max .5
     */
    const inset = .2
    const draw_width = cell_width * (1 - (inset * 2))
    const draw_height = cell_height * (1 - (inset * 2))

    // When the current state contains a solution, the path is added to a set for easier lookup
    const result_path = new PositionSet();
    if (currentState?.result !== undefined) {
        let node = currentState.result
        while (node.parent != null) {
            result_path.add(node.position)
            node = node.parent
        }
    }

    // go through all rows of the grid
    for (const [row_idx, cols] of enumerate(labyrinth.grid)) {
        // go through all the cells of each row
        for (const [col_idx, cell] of enumerate(cols)) {
            // the drawing start position for the current cell
            const start_pos_x = col_idx * cell_width + cell_width * inset
            const start_pos_y = row_idx * cell_height + cell_height * inset

            let color = null
            if (cell === CellType.OBSTACLE) {
                color = COLOR_OBSTACLE
            } else if (cell === CellType.START) {
                color = COLOR_START
            } else if (cell === CellType.GOAL) {
                color = COLOR_GOAL
            } else if (currentState !== undefined) {
                const pos = new Position(row_idx, col_idx)

                if(result_path.has(pos)) {
                    color = COLOR_PATH
                }else if (currentState.visited_positions.has(pos)) {
                    color = COLOR_VISITED
                }else if (currentState.frontier_positions.has(pos)) {
                    color = COLOR_FRONTIER
                }
            }

            if (color !== null) {
                ctx.fillStyle = color
                ctx.fillRect(start_pos_x, start_pos_y, draw_width, draw_height)
            }
        }
    }

}

function select_algorithm(algorithm_idx: number) {
    if(labyrinth === undefined) {
        labyrinth = create_labyrinth();
    }
    if (algorithm_idx >= ALGORITHM_LIST.length) {
        alert(`Invalid algorithm idx ${algorithm_idx}! Max index: ${ALGORITHM_LIST.length - 1}`);
        return
    }

    const [newAlgorithm, name] = ALGORITHM_LIST[algorithm_idx];
    selectedAlgorithm = newAlgorithm;

    setTitle("Search Algorithm - " + name);


    start_algorithm();
}

function handle_event(e: KeyboardEvent) {
    if(e.key.length != 1) {
        return;
    }
    const code = e.key.charCodeAt(0);
    if(code >= '0'.charCodeAt(0) && code <= '9'.charCodeAt(0)) {
        select_algorithm(code - '1'.charCodeAt(0))
        return
    }

    if(e.key == 'r') {
        labyrinth = create_labyrinth();
        drawLabyrinth();
        start_algorithm();
        return
    }

    if (e.key == 'p') {
        if(active) {
            active = false;
        }else {
            active = true;
            run_algorithm_step();
        }
        return;
    }

    if(e.key == 'f') {
        simulated = !simulated;
    }
}

function start_algorithm() {
    if(selectedAlgorithm === undefined) return;

    simulated = true;
    active = true;

    if(labyrinth === undefined) {
        labyrinth = create_labyrinth();
    }

    runningAlgorithm = selectedAlgorithm(labyrinth, new AlgorithmNode(START_POS));

    run_algorithm_step()

}

function stop_algorithm() {
    runningAlgorithm = undefined;
}

function run_algorithm_step() {
    if(runningAlgorithm === undefined || !active) return;

    currentState = runningAlgorithm.next().value;

    if(currentState === undefined) {
        return stop_algorithm();
    }

    if(simulated || currentState.result !== undefined) {
        drawLabyrinth();
    }

    requestAnimationFrame(run_algorithm_step);
}

function create_labyrinth(): Labyrinth {
    return new Labyrinth(LAB_ROWS, LAB_COLS, OBSTACLE_DENSITY, START_POS, END_POS);
}

window.addEventListener("keydown", handle_event);
window.onresize = setSize

labyrinth = create_labyrinth();
setSize();
